{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"intersections"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIntersection","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeIntersection","text":"NVibeIntersection"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"maneuver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuver","text":"NVibeManeuver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"walkingSide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streetName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibestep\/init(distance:duration:geometry:intersections:maneuver:walkingside:streetname:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/init(distance:duration:geometry:intersections:maneuver:walkingSide:streetName:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"intersections"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NVibeIntersection","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeIntersection"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"maneuver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeManeuver","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"walkingSide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streetName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(distance:duration:geometry:intersections:maneuver:walkingSide:streetName:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:14NVDirectionKit9NVibeStepC8distance8duration8geometry13intersections8maneuver11walkingSide10streetNameACSd_SdSSSayAA0C12IntersectionCGAA0C8ManeuverCS2Stcfc","modules":[{"name":"NVDirectionKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep"]]},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/init(distance:duration:geometry:intersections:maneuver:walkingSide:streetName:)":{"role":"symbol","title":"init(distance:duration:geometry:intersections:maneuver:walkingSide:streetName:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"intersections"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NVibeIntersection","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeIntersection"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"maneuver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeManeuver","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"walkingSide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streetName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/init(distance:duration:geometry:intersections:maneuver:walkingSide:streetName:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep\/init(distance:duration:geometry:intersections:maneuver:walkingside:streetname:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","title":"NVDirectionKit","abstract":[{"type":"text","text":"Obtain route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver":{"role":"symbol","title":"NVibeManeuver","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeManeuver"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeManeuver"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"role":"symbol","title":"NVibeStep","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeStep"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"url":"\/documentation\/nvdirectionkit\/nvibestep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIntersection":{"role":"symbol","title":"NVibeIntersection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeIntersection"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIntersection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeIntersection"}],"url":"\/documentation\/nvdirectionkit\/nvibeintersection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/title","value":"NVibeManeuver"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/fragments","value":[{"kind":"identifier","text":"NVibeManeuver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title","value":"NVibeStep"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments","value":[{"kind":"identifier","text":"NVibeStep"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIntersection\/title","value":"NVibeIntersection"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIntersection\/fragments","value":[{"kind":"identifier","text":"NVibeIntersection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}