{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nviberouteoption\/forbiddenobstacles"]}],"metadata":{"title":"forbiddenObstacles","symbolKind":"property","modules":[{"name":"NVDirectionKit"}],"externalID":"s:14NVDirectionKit16NVibeRouteOptionC18forbiddenObstaclesSaySSGvp","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forbiddenObstacles"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"forbiddenObstacles","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/forbiddenObstacles"},"kind":"symbol","sections":[],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/forbiddenObstacles":{"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/forbiddenObstacles","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forbiddenObstacles"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"url":"\/documentation\/nvdirectionkit\/nviberouteoption\/forbiddenobstacles","abstract":[],"role":"symbol","title":"forbiddenObstacles","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption":{"title":"NVibeRouteOption","url":"\/documentation\/nvdirectionkit\/nviberouteoption","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeRouteOption","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeRouteOption","kind":"identifier"}],"abstract":[{"type":"text","text":"The option for walking route."}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"NVibeRouteOption","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/title","op":"replace"},{"value":[{"text":"NVibeRouteOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/fragments"},{"value":[{"text":"NVibeRouteOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/navigatorTitle","op":"replace"}]}]}