{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nviberouteoption\/vialinks"]}],"metadata":{"modules":[{"name":"NVDirectionKit"}],"externalID":"s:14NVDirectionKit16NVibeRouteOptionC8viaLinksSayAA4LinkCGvp","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"viaLinks","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)Link","kind":"typeIdentifier","text":"Link"},{"kind":"text","text":"]"}],"symbolKind":"property","title":"viaLinks"},"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/viaLinks","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"viaLinks","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Link","kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)Link"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption":{"title":"NVibeRouteOption","url":"\/documentation\/nvdirectionkit\/nviberouteoption","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeRouteOption","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeRouteOption","kind":"identifier"}],"abstract":[{"type":"text","text":"The option for walking route."}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/viaLinks":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/viaLinks","abstract":[],"role":"symbol","title":"viaLinks","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"viaLinks","kind":"identifier"},{"kind":"text","text":": ["},{"text":"Link","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)Link"},{"kind":"text","text":"]"}],"url":"\/documentation\/nvdirectionkit\/nviberouteoption\/vialinks"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/Link":{"url":"\/documentation\/nvdirectionkit\/link","type":"topic","title":"Link","navigatorTitle":[{"kind":"identifier","text":"Link"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Link","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link","abstract":[{"type":"text","text":"The link along an alternative walking route."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/title","value":"NVibeRouteOption"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/fragments","value":[{"kind":"identifier","text":"NVibeRouteOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/navigatorTitle","value":[{"text":"NVibeRouteOption","kind":"identifier"}]},{"value":"Link","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/fragments","value":[{"kind":"identifier","text":"Link"}]},{"op":"replace","value":[{"kind":"identifier","text":"Link"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/navigatorTitle"}]}]}