{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nviberouteoption\/withcrossing"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"withCrossing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withCrossing"},"metadata":{"modules":[{"name":"NVDirectionKit"}],"roleHeading":"Instance Property","externalID":"s:14NVDirectionKit16NVibeRouteOptionC12withCrossingSbvp","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"withCrossing","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","title":"withCrossing","symbolKind":"property"},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption":{"title":"NVibeRouteOption","url":"\/documentation\/nvdirectionkit\/nviberouteoption","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeRouteOption","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeRouteOption","kind":"identifier"}],"abstract":[{"type":"text","text":"The option for walking route."}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/withCrossing":{"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withCrossing","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCrossing"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"role":"symbol","url":"\/documentation\/nvdirectionkit\/nviberouteoption\/withcrossing","title":"withCrossing"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"NVibeRouteOption","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/title","op":"replace"},{"value":[{"text":"NVibeRouteOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/navigatorTitle","op":"replace","value":[{"text":"NVibeRouteOption","kind":"identifier"}]}]}]}