{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intersections"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIntersection","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeIntersection","text":"NVibeIntersection"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibestep\/intersections"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/intersections","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intersections"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NVibeIntersection","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeIntersection"},{"kind":"text","text":"]"}],"title":"intersections","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:14NVDirectionKit9NVibeStepC13intersectionsSayAA0C12IntersectionCGvp","modules":[{"name":"NVDirectionKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep"]]},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"role":"symbol","title":"NVibeStep","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeStep"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"url":"\/documentation\/nvdirectionkit\/nvibestep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","title":"NVDirectionKit","abstract":[{"type":"text","text":"Obtain route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/intersections":{"role":"symbol","title":"intersections","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intersections"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NVibeIntersection","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeIntersection"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/intersections","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep\/intersections"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIntersection":{"role":"symbol","title":"NVibeIntersection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeIntersection"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIntersection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeIntersection"}],"url":"\/documentation\/nvdirectionkit\/nvibeintersection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title","value":"NVibeStep"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments","value":[{"kind":"identifier","text":"NVibeStep"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIntersection\/title","value":"NVibeIntersection"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIntersection\/fragments","value":[{"kind":"identifier","text":"NVibeIntersection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}