{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Returns a custom walking route from a set of coordinates asynchronously."}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:completion:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getCustomNavigationRoute(from:to:with:language:completion:)"],"title":"Requesting walking route","anchor":"Requesting-walking-route","generated":true}],"metadata":{"externalID":"s:14NVDirectionKit0A0C24getCustomNavigationRoute4from2to4with8languageAA05NVibeF0C5route_Sd17startingDirectiontAA0K8LocationC_ANSaySo22CLLocationCoordinate2DVGSStYaKF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getCustomNavigationRoute","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"language"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> (route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"kind":"text","text":", startingDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection"},{"kind":"text","text":")"}],"title":"getCustomNavigationRoute(from:to:with:language:)","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"NVDirectionKit"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getCustomNavigationRoute"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"text":"startLocation","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"text":"endLocation","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"coordinates","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"language"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" = \"en\") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> (route"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute","kind":"typeIdentifier","text":"NVibeRoute"},{"kind":"text","text":", startingDirection"},{"text":": ","kind":"text"},{"text":"CLLocationDirection","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"startLocation","content":[{"inlineContent":[{"text":"The departure of the route.","type":"text"}],"type":"paragraph"}]},{"name":"endLocation","content":[{"type":"paragraph","inlineContent":[{"text":"The arrival of the route.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The list of coordinates to create the custom route. Need at least two coordinates.","type":"text"}],"type":"paragraph"}],"name":"coordinates"},{"name":"language","content":[{"type":"paragraph","inlineContent":[{"text":"The language of instruction (English (en), French (fr), Dutch (nl), Spanish (es), German (de)). The default value of this property is ","type":"text"},{"code":"en","type":"codeVoice"},{"text":".","type":"text"}]}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"An asynchronously-delivered tuple that contains the custom walking route and the starting direction.","type":"text"}]}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getCustomNavigationRoute(from:to:with:language:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvdirection\/getcustomnavigationroute(from:to:with:language:)"]}],"sections":[],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getStartingDirection(from:to:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStartingDirection"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"getStartingDirection(from:to:)","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getstartingdirection(from:to:)","kind":"symbol","abstract":[{"text":"Returns the starting direction of a walking route asynchronously.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:)","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"title":"NVibeLocation","url":"\/documentation\/nvdirectionkit\/nvibelocation","abstract":[{"type":"text","text":"The address and coordinates of a location."}],"navigatorTitle":[{"text":"NVibeLocation","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeLocation","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"role":"symbol","kind":"symbol","title":"NVDirection","url":"\/documentation\/nvdirectionkit\/nvdirection","abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"navigatorTitle":[{"kind":"identifier","text":"NVDirection"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getCustomNavigationRoute(from:to:with:language:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getCustomNavigationRoute","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"text":": [","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"language"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ((route"},{"text":": ","kind":"text"},{"text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute","kind":"typeIdentifier"},{"kind":"text","text":", startingDirection"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","kind":"typeIdentifier","text":"CLLocationDirection"},{"kind":"text","text":")?, "},{"preciseIdentifier":"s:14NVDirectionKit10RouteErrorO","kind":"typeIdentifier","text":"RouteError"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"title":"getCustomNavigationRoute(from:to:with:language:completion:)","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getcustomnavigationroute(from:to:with:language:completion:)","kind":"symbol","abstract":[{"text":"Returns a custom walking route from a set of coordinates from completion handler.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getCustomNavigationRoute(from:to:with:language:completion:)","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getCustomNavigationRoute(from:to:with:language:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvdirection\/getcustomnavigationroute(from:to:with:language:)","abstract":[{"text":"Returns a custom walking route from a set of coordinates asynchronously.","type":"text"}],"title":"getCustomNavigationRoute(from:to:with:language:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getCustomNavigationRoute"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":"], "},{"text":"language","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> (route"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute","kind":"typeIdentifier","text":"NVibeRoute"},{"text":", startingDirection","kind":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getCustomNavigationRoute(from:to:with:language:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getStartingDirection(from:to:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getStartingDirection","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"RouteError","preciseIdentifier":"s:14NVDirectionKit10RouteErrorO"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"getStartingDirection(from:to:completion:)","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getstartingdirection(from:to:completion:)","kind":"symbol","abstract":[{"type":"text","text":"Returns the starting direction of a walking route from completion handler."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:completion:)","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute":{"abstract":[{"text":"The walking route received when requesting walking route.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRoute"}],"title":"NVibeRoute","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute","role":"symbol","navigatorTitle":[{"text":"NVibeRoute","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","value":"NVibeLocation","op":"replace"},{"value":[{"text":"NVibeLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeLocation"}]},{"op":"replace","value":"NVDirection","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title"},{"value":[{"kind":"identifier","text":"NVDirection"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/navigatorTitle","value":[{"kind":"identifier","text":"NVDirection"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/title","op":"replace","value":"NVibeRoute"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/fragments","value":[{"kind":"identifier","text":"NVibeRoute"}]},{"value":[{"text":"NVibeRoute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/navigatorTitle"}]}]}