{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getMultimodalRoute","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"text":"startLocation","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"text":"endLocation","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onlyFullWalking"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"withFullWalkingAlternative"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"text":"NVibeTransitInformation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Mode","preciseIdentifier":"s:14NVDirectionKit23NVibeTransitInformationC4ModeO","kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/Mode"},{"text":"] = []) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> [","kind":"text"},{"text":"NVibeMultimodalRoute","kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The departure of the route.","type":"text"}]}],"name":"startLocation"},{"name":"endLocation","content":[{"type":"paragraph","inlineContent":[{"text":"The arrival of the route.","type":"text"}]}]},{"name":"onlyFullWalking","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set "},{"type":"codeVoice","code":"true"},{"type":"text","text":" to get only full walking route without transit. Set "},{"type":"codeVoice","code":"false"},{"text":" to additionnaly include route with transit. The default value of this property is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Set ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":" to get full walking route alternative. Set "},{"type":"codeVoice","code":"false"},{"text":" to get only one full walking route. The default value of this property is ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]}],"name":"withFullWalkingAlternative"}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"An asynchronously-delivered value that contains a list of multimodal route."}],"type":"paragraph"}]}],"abstract":[{"text":"Returns multimodal routes asynchronously.","type":"text"}],"metadata":{"title":"getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:)","modules":[{"name":"NVDirectionKit"}],"externalID":"s:14NVDirectionKit0A0C18getMultimodalRoute4from2to15onlyFullWalking04withiJ11Alternative5avoidSayAA05NVibedE0CGAA0N8LocationC_ANS2bSayAA0N18TransitInformationC4ModeOGtYaKF","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getMultimodalRoute"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier","text":"NVibeLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onlyFullWalking"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"withFullWalkingAlternative","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"avoid","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation","text":"NVibeTransitInformation","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Mode","kind":"typeIdentifier","preciseIdentifier":"s:14NVDirectionKit23NVibeTransitInformationC4ModeO"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> ["},{"text":"NVibeMultimodalRoute","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute"},{"kind":"text","text":"]"}],"symbolKind":"method","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"]]},"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvdirection\/getmultimodalroute(from:to:onlyfullwalking:withfullwalkingalternative:avoid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"role":"symbol","kind":"symbol","title":"NVDirection","url":"\/documentation\/nvdirectionkit\/nvdirection","abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"navigatorTitle":[{"kind":"identifier","text":"NVDirection"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation":{"navigatorTitle":[{"text":"NVibeTransitInformation","kind":"identifier"}],"title":"NVibeTransitInformation","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeTransitInformation","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/Mode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Mode","kind":"identifier"}],"title":"NVibeTransitInformation.Mode","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/Mode","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Mode"}],"abstract":[{"text":"Constants that describe the mode of the transit multimodal step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/mode"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"title":"NVibeLocation","url":"\/documentation\/nvdirectionkit\/nvibelocation","abstract":[{"type":"text","text":"The address and coordinates of a location."}],"navigatorTitle":[{"text":"NVibeLocation","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeLocation","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:)":{"role":"symbol","title":"getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMultimodalRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier","text":"NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onlyFullWalking"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withFullWalkingAlternative"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"avoid","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"NVibeTransitInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14NVDirectionKit23NVibeTransitInformationC4ModeO","text":"Mode","kind":"typeIdentifier"},{"text":"]) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"NVibeMultimodalRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"Returns multimodal routes asynchronously."}],"url":"\/documentation\/nvdirectionkit\/nvdirection\/getmultimodalroute(from:to:onlyfullwalking:withfullwalkingalternative:avoid:)","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:)","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute":{"url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalRoute"}],"title":"NVibeMultimodalRoute","role":"symbol","abstract":[{"text":"The multimodal route received when requesting multimodal route.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalRoute"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"NVDirection","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments","op":"replace","value":[{"text":"NVDirection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/navigatorTitle","value":[{"kind":"identifier","text":"NVDirection"}],"op":"replace"},{"value":"NVibeTransitInformation","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/fragments","value":[{"text":"NVibeTransitInformation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NVibeTransitInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","value":"NVibeLocation"},{"value":[{"text":"NVibeLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/navigatorTitle","op":"replace","value":[{"text":"NVibeLocation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/title","value":"NVibeMultimodalRoute"},{"value":[{"text":"NVibeMultimodalRoute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/fragments"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeMultimodalRoute"}],"op":"replace"}]}]}