{"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvdirection\/getnavigationroute(from:to:sidestreet:language:withobstacle:forbiddenobstacles:withinformationpoint:withalternativepolyline:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getNavigationRoute"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"startLocation"},{"text":": ","kind":"text"},{"text":"NVibeLocation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"text":" ","kind":"text"},{"text":"endLocation","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":", ","kind":"text"},{"text":"sideStreet","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SideStreet","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","preciseIdentifier":"s:14NVDirectionKit10SideStreetO","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"language","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"en\", "},{"kind":"externalParam","text":"withObstacle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"text":"forbiddenObstacles","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"withInformationPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"withAlternativePolyline","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = false) "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> (route"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute","kind":"typeIdentifier","text":"NVibeRoute"},{"text":", startingDirection","kind":"text"},{"kind":"text","text":": "},{"text":"CLLocationDirection","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":", solutionFound"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The departure of the route.","type":"text"}]}],"name":"startLocation"},{"name":"endLocation","content":[{"type":"paragraph","inlineContent":[{"text":"The arrival of the route.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The side of the street from where the user starts."}],"type":"paragraph"}],"name":"sideStreet"},{"name":"language","content":[{"inlineContent":[{"type":"text","text":"The language of instruction (English (en), French (fr), Dutch (nl), Spanish (es), German (de)). The default value of this property is "},{"type":"codeVoice","code":"en"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"withObstacle","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set "},{"type":"codeVoice","code":"true"},{"type":"text","text":" to include "},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","isActive":true,"type":"reference"},{"text":" on the route. The default value of this property is ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"text":"Set a list of ","type":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/id","isActive":true,"type":"reference"},{"type":"text","text":" to avoid them if possible."}],"type":"paragraph"}],"name":"forbiddenObstacles"},{"name":"withInformationPoint","content":[{"inlineContent":[{"type":"text","text":"Set "},{"type":"codeVoice","code":"true"},{"type":"text","text":" to include "},{"type":"reference","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint","isActive":true},{"type":"text","text":" on the route. The default value of this property is "},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Set to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" to include an ","type":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/alternativeGeometry","isActive":true,"type":"reference"},{"text":" shifted on the side of the street instead of the middle of the route. The default geometry is always available with ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/geometry","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"withAlternativePolyline"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"An asynchronously-delivered tuple that contains the walking route, the starting direction and a boolean value that indicates whether the route is crossable."}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:)"},"abstract":[{"text":"Returns a walking route asynchronously.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","modules":[{"name":"NVDirectionKit"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"s:14NVDirectionKit0A0C18getNavigationRoute4from2to10sideStreet8language12withObstacle18forbiddenObstacles0K16InformationPoint0K19AlternativePolylineAA05NVibeE0C5route_Sd17startingDirectionSb13solutionFoundtAA0S8LocationC_AsA04SideI0OSgSSSbSaySSGS2btYaKF","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getNavigationRoute"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier","text":"NVibeLocation"},{"text":", ","kind":"text"},{"text":"sideStreet","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14NVDirectionKit10SideStreetO","text":"SideStreet"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"language"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withObstacle"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forbiddenObstacles"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"withInformationPoint"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withAlternativePolyline"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> (route","kind":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute","text":"NVibeRoute"},{"text":", startingDirection","kind":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection"},{"text":", solutionFound","kind":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:)"},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"title":"NVibeLocation","url":"\/documentation\/nvdirectionkit\/nvibelocation","abstract":[{"type":"text","text":"The address and coordinates of a location."}],"navigatorTitle":[{"text":"NVibeLocation","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeLocation","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute":{"abstract":[{"text":"The walking route received when requesting walking route.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRoute"}],"title":"NVibeRoute","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute","role":"symbol","navigatorTitle":[{"text":"NVibeRoute","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"role":"symbol","kind":"symbol","title":"NVDirection","url":"\/documentation\/nvdirectionkit\/nvdirection","abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"navigatorTitle":[{"kind":"identifier","text":"NVDirection"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/geometry":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/geometry","url":"\/documentation\/nvdirectionkit\/nviberoute\/geometry","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"geometry","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","abstract":[{"text":"The geometry (encoded with an accuracy of 6) of the walking route.","type":"text"}],"kind":"symbol","title":"geometry","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/alternativeGeometry":{"abstract":[{"type":"text","text":"The alternative geometry (encoded with an accuracy of 6) of the walking route."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alternativeGeometry"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"alternativeGeometry","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/alternativeGeometry","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/alternativegeometry","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:)":{"type":"topic","abstract":[{"text":"Returns a walking route asynchronously.","type":"text"}],"title":"getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:)","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:)","kind":"symbol","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvdirection\/getnavigationroute(from:to:sidestreet:language:withobstacle:forbiddenobstacles:withinformationpoint:withalternativepolyline:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getNavigationRoute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier","text":"NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sideStreet","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SideStreet","preciseIdentifier":"s:14NVDirectionKit10SideStreetO"},{"kind":"text","text":"?, "},{"text":"language","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"withObstacle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forbiddenObstacles","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"withInformationPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withAlternativePolyline"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> (route"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute","text":"NVibeRoute","kind":"typeIdentifier"},{"kind":"text","text":", startingDirection"},{"kind":"text","text":": "},{"text":"CLLocationDirection","kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":", solutionFound"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","kind":"symbol","abstract":[{"type":"text","text":"The obstacle along a route."}],"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeobstacle","navigatorTitle":[{"text":"NVibeObstacle","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeObstacle","kind":"identifier"}],"title":"NVibeObstacle"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeInformationPoint":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeInformationPoint"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint","url":"\/documentation\/nvdirectionkit\/nvibeinformationpoint","type":"topic","title":"NVibeInformationPoint","role":"symbol","abstract":[{"type":"text","text":"The information point along a route."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeInformationPoint"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SideStreet"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","url":"\/documentation\/nvdirectionkit\/sidestreet","title":"SideStreet","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SideStreet"}],"role":"symbol","abstract":[{"type":"text","text":"The side of the street."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle/id":{"abstract":[{"type":"text","text":"The id of the obstacle."}],"type":"topic","title":"id","url":"\/documentation\/nvdirectionkit\/nvibeobstacle\/id","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/id"}},"variantOverrides":[{"patch":[{"value":"NVibeLocation","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","value":[{"text":"NVibeLocation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeLocation"}],"op":"replace"},{"value":"NVibeRoute","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/title"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/fragments","value":[{"kind":"identifier","text":"NVibeRoute"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/navigatorTitle","value":[{"text":"NVibeRoute","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title","value":"NVDirection","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"NVDirection"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/navigatorTitle","value":[{"kind":"identifier","text":"NVDirection"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/title","value":"NVibeObstacle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/fragments","value":[{"text":"NVibeObstacle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/navigatorTitle","op":"replace","value":[{"text":"NVibeObstacle","kind":"identifier"}]},{"value":"NVibeInformationPoint","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/title"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/fragments","value":[{"kind":"identifier","text":"NVibeInformationPoint"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeInformationPoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}