{"metadata":{"symbolKind":"property","modules":[{"name":"NVDirectionKit"}],"externalID":"s:14NVDirectionKit19NVibeTransitionDataC21currentMultimodalStepAA0cgH0Cvp","title":"currentMultimodalStep","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"currentMultimodalStep","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeMultimodalStep","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep"}],"roleHeading":"Instance Property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData"]]},"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibetransitiondata\/currentmultimodalstep"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/currentMultimodalStep"},"kind":"symbol","sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/previousMultimodalStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/nextMultimodalStep"],"title":"Getting the transition data attributes","anchor":"Getting-the-transition-data-attributes","generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentMultimodalStep"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","text":"NVibeMultimodalStep"}]}],"kind":"declarations"}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData/nextMultimodalStep":{"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata\/nextmultimodalstep","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextMultimodalStep","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","text":"NVibeMultimodalStep","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/nextMultimodalStep","abstract":[],"title":"nextMultimodalStep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData":{"title":"NVibeTransitionData","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata","navigatorTitle":[{"kind":"identifier","text":"NVibeTransitionData"}],"abstract":[{"text":"The transition data for walking route.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeTransitionData"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData/currentMultimodalStep":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"currentMultimodalStep","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","kind":"typeIdentifier","text":"NVibeMultimodalStep"}],"url":"\/documentation\/nvdirectionkit\/nvibetransitiondata\/currentmultimodalstep","type":"topic","abstract":[],"title":"currentMultimodalStep","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/currentMultimodalStep","role":"symbol","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData/previousMultimodalStep":{"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata\/previousmultimodalstep","title":"previousMultimodalStep","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previousMultimodalStep","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NVibeMultimodalStep","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/previousMultimodalStep","type":"topic","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeMultimodalStep","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","abstract":[{"type":"text","text":"The multimodal step inside multimodal route."}],"type":"topic","title":"NVibeMultimodalStep","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalStep"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/title","value":"NVibeTransitionData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/fragments","value":[{"kind":"identifier","text":"NVibeTransitionData"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/navigatorTitle","value":[{"text":"NVibeTransitionData","kind":"identifier"}],"op":"replace"},{"value":"NVibeMultimodalStep","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/title"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/fragments","op":"replace","value":[{"text":"NVibeMultimodalStep","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NVibeMultimodalStep"}]}]}]}