{"abstract":[{"type":"text","text":"The link along an alternative walking route."}],"relationshipsSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/Se","doc:\/\/com.nvibe.NVDirectionKit\/SE","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet"],"anchor":"Global","title":"Global","generated":true}],"metadata":{"title":"Link","externalID":"c:@M@NVDirectionKit@objc(cs)Link","modules":[{"name":"NVDirectionKit"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Link"}],"symbolKind":"class","roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"Link","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Link","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link","isActive":true},{"text":" object contains an id. When calculating alternative walking multimodal route, ","type":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link","isActive":true,"type":"reference"},{"text":" objects are provided inside ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/links","isActive":true},{"type":"text","text":" and can be used with "},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","isActive":true,"type":"reference"},{"type":"text","text":" when requesting a walking route with "},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:option:)","isActive":true,"type":"reference"},{"text":" to force the calculated walking route to pass through specific street.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/link"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nvdirectionkit\/link"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"topicSections":[{"title":"Getting the link point attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link\/id"],"anchor":"Getting-the-link-point-attributes"},{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link\/init(from:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link"},"kind":"symbol","sections":[],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/Link/init(from:)":{"abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link\/init(from:)","type":"topic","title":"init(from:)","url":"\/documentation\/nvdirectionkit\/link\/init(from:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","kind":"symbol","abstract":[{"type":"text","text":"The obstacle along a route."}],"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeobstacle","navigatorTitle":[{"text":"NVibeObstacle","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeObstacle","kind":"identifier"}],"title":"NVibeObstacle"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeInformationPoint":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeInformationPoint"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint","url":"\/documentation\/nvdirectionkit\/nvibeinformationpoint","type":"topic","title":"NVibeInformationPoint","role":"symbol","abstract":[{"type":"text","text":"The information point along a route."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeInformationPoint"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption":{"title":"NVibeRouteOption","url":"\/documentation\/nvdirectionkit\/nviberouteoption","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeRouteOption","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeRouteOption","kind":"identifier"}],"abstract":[{"type":"text","text":"The option for walking route."}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP"},"doc://com.nvibe.NVDirectionKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH"},"doc://com.nvibe.NVDirectionKit/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/Se"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"title":"NVibeLocation","url":"\/documentation\/nvdirectionkit\/nvibelocation","abstract":[{"type":"text","text":"The address and coordinates of a location."}],"navigatorTitle":[{"text":"NVibeLocation","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeLocation","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ"},"doc://com.nvibe.NVDirectionKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getNavigationRoute(from:to:sideStreet:option:)":{"type":"topic","title":"getNavigationRoute(from:to:sideStreet:option:)","abstract":[{"type":"text","text":"Returns a walking route with crossing asynchronously using "},{"isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","type":"reference"},{"type":"text","text":"."}],"url":"\/documentation\/nvdirectionkit\/nvdirection\/getnavigationroute(from:to:sidestreet:option:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getNavigationRoute","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"text":"sideStreet","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14NVDirectionKit10SideStreetO","text":"SideStreet"},{"text":"?, ","kind":"text"},{"text":"option","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRouteOption","kind":"typeIdentifier","text":"NVibeRouteOption"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> (route"},{"text":": ","kind":"text"},{"text":"NVibeRoute","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"kind":"text","text":", startingDirection"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"},{"text":", solutionFound","kind":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:option:)","role":"symbol","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SE"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/Link/id":{"url":"\/documentation\/nvdirectionkit\/link\/id","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link\/id","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"The id of the link.","type":"text"}],"kind":"symbol","title":"id","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SideStreet"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","url":"\/documentation\/nvdirectionkit\/sidestreet","title":"SideStreet","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SideStreet"}],"role":"symbol","abstract":[{"type":"text","text":"The side of the street."}]},"doc://com.nvibe.NVDirectionKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation":{"url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation","abstract":[{"type":"text","text":"The address and coordinates of a indoor location."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeIndoorLocation"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeIndoorLocation"}],"role":"symbol","kind":"symbol","title":"NVibeIndoorLocation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/links":{"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/links","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/links","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"links"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)Link","kind":"typeIdentifier","text":"Link"},{"text":"]?","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"text":"The links used by alternative walking multimodal step.","type":"text"}],"title":"links","role":"symbol"},"doc://com.nvibe.NVDirectionKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/Link":{"url":"\/documentation\/nvdirectionkit\/link","type":"topic","title":"Link","navigatorTitle":[{"kind":"identifier","text":"Link"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Link","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link","abstract":[{"type":"text","text":"The link along an alternative walking route."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"Link","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"text":"Link","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"Link","kind":"identifier"}],"op":"replace"},{"value":null,"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"value":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint"],"anchor":"Global","title":"Global","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"Link","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/title","value":"NVibeObstacle"},{"value":[{"kind":"identifier","text":"NVibeObstacle"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/navigatorTitle","value":[{"text":"NVibeObstacle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/title","op":"replace","value":"NVibeInformationPoint"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/fragments","op":"replace","value":[{"text":"NVibeInformationPoint","kind":"identifier"}]},{"value":[{"text":"NVibeInformationPoint","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/title","op":"replace","value":"NVibeRouteOption"},{"value":[{"text":"NVibeRouteOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeRouteOption"}]},{"value":"NVibeLocation","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","op":"replace","value":[{"text":"NVibeLocation","kind":"identifier"}]},{"op":"replace","value":[{"text":"NVibeLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/title","op":"replace","value":"NVibeIndoorLocation"},{"value":[{"text":"NVibeIndoorLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/fragments"},{"value":[{"text":"NVibeIndoorLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/title","value":"Link"},{"value":[{"kind":"identifier","text":"Link"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/fragments"},{"value":[{"text":"Link","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}