{"topicSections":[{"title":"Getting the option attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/language","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withObstacle","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withAlternativeGeometry"],"anchor":"Getting-the-option-attributes"},{"generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/forbiddenObstacles","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/transitionData","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/viaLinks","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withCrossing","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withInformationPoint"],"anchor":"Instance-Properties","title":"Instance Properties"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError"],"title":"Route","generated":true,"anchor":"Route"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/nvdirectionkit\/nviberouteoption"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nvdirectionkit\/nviberouteoption"]}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeRouteOption","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","type":"reference","isActive":true},{"text":" object keeps your option when requesting the walking route for navigation reroute.","type":"text"}]}],"kind":"content"}],"kind":"symbol","sections":[],"abstract":[{"text":"The option for walking route.","type":"text"}],"metadata":{"role":"symbol","symbolKind":"class","modules":[{"name":"NVDirectionKit"}],"title":"NVibeRouteOption","externalID":"c:@M@NVDirectionKit@objc(cs)NVibeRouteOption","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeRouteOption","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeRouteOption"}],"roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg":{"abstract":[{"type":"text","text":"The walking leg inside walking route."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeLeg","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeleg","navigatorTitle":[{"kind":"identifier","text":"NVibeLeg"}],"role":"symbol","type":"topic","title":"NVibeLeg"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError":{"abstract":[{"text":"Constants that describe error related to walking route calculation.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RouteError"}],"role":"symbol","url":"\/documentation\/nvdirectionkit\/routeerror","navigatorTitle":[{"kind":"identifier","text":"RouteError"}],"type":"topic","title":"RouteError","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/transitionData":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"transitionData","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitionData","text":"NVibeTransitionData"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/transitionData","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nviberouteoption\/transitiondata","role":"symbol","type":"topic","title":"transitionData"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/language":{"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/language","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"language","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","url":"\/documentation\/nvdirectionkit\/nviberouteoption\/language","type":"topic","title":"language","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","url":"\/documentation\/nvdirectionkit\/nvibestep","type":"topic","title":"NVibeStep","role":"symbol","abstract":[{"text":"The walking step inside walking leg.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeStep","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver":{"title":"NVibeManeuver","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","abstract":[{"type":"text","text":"The maneuver of the walking step."}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeManeuver","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeManeuver"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/withObstacle":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"withObstacle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withObstacle","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nviberouteoption\/withobstacle","role":"symbol","type":"topic","title":"withObstacle"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute":{"abstract":[{"text":"The walking route received when requesting walking route.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRoute"}],"title":"NVibeRoute","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute","role":"symbol","navigatorTitle":[{"text":"NVibeRoute","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption":{"title":"NVibeRouteOption","url":"\/documentation\/nvdirectionkit\/nviberouteoption","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeRouteOption","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeRouteOption","kind":"identifier"}],"abstract":[{"type":"text","text":"The option for walking route."}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/viaLinks":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/viaLinks","abstract":[],"role":"symbol","title":"viaLinks","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"viaLinks","kind":"identifier"},{"kind":"text","text":": ["},{"text":"Link","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)Link"},{"kind":"text","text":"]"}],"url":"\/documentation\/nvdirectionkit\/nviberouteoption\/vialinks"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/forbiddenObstacles":{"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/forbiddenObstacles","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forbiddenObstacles"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"url":"\/documentation\/nvdirectionkit\/nviberouteoption\/forbiddenobstacles","abstract":[],"role":"symbol","title":"forbiddenObstacles","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/withInformationPoint":{"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nviberouteoption\/withinformationpoint","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"withInformationPoint"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withInformationPoint","abstract":[],"title":"withInformationPoint"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/withAlternativeGeometry":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"withAlternativeGeometry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withAlternativeGeometry","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/nvdirectionkit\/nviberouteoption\/withalternativegeometry","kind":"symbol","title":"withAlternativeGeometry"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject","title":"NSObject"},"doc://com.nvibe.NVDirectionKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.nvibe.NVDirectionKit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH","title":"Swift.Hashable"},"doc://com.nvibe.NVDirectionKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ","title":"Swift.Equatable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/withCrossing":{"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withCrossing","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCrossing"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"role":"symbol","url":"\/documentation\/nvdirectionkit\/nviberouteoption\/withcrossing","title":"withCrossing"},"doc://com.nvibe.NVDirectionKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.nvibe.NVDirectionKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuverDetail":{"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuverdetail","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","kind":"symbol","title":"NVibeManeuverDetail","abstract":[{"type":"text","text":"The detail inside maneuver."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeManeuverDetail"}],"navigatorTitle":[{"text":"NVibeManeuverDetail","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"NVibeRouteOption"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"NVibeRouteOption"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"NVibeRouteOption","kind":"identifier"}]},{"value":null,"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"Route","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail"],"title":"Route"}],"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeRouteOption","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"NVibeLeg","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/title"},{"value":[{"text":"NVibeLeg","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/fragments"},{"value":[{"text":"NVibeLeg","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title","value":"NVibeStep"},{"value":[{"kind":"identifier","text":"NVibeStep"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments","op":"replace"},{"op":"replace","value":[{"text":"NVibeStep","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/navigatorTitle"},{"op":"replace","value":"NVibeManeuver","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/title"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/fragments","value":[{"text":"NVibeManeuver","kind":"identifier"}],"op":"replace"},{"value":[{"text":"NVibeManeuver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/title","op":"replace","value":"NVibeRoute"},{"value":[{"kind":"identifier","text":"NVibeRoute"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NVibeRoute"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/navigatorTitle","op":"replace"},{"value":"NVibeRouteOption","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/title"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/fragments","value":[{"kind":"identifier","text":"NVibeRouteOption"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/navigatorTitle","op":"replace","value":[{"text":"NVibeRouteOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/title","value":"NVibeManeuverDetail","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/fragments","value":[{"kind":"identifier","text":"NVibeManeuverDetail"}],"op":"replace"},{"value":[{"text":"NVibeManeuverDetail","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/navigatorTitle","op":"replace"}]}]}