{"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeManeuver"}]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/Se","doc:\/\/com.nvibe.NVDirectionKit\/SE","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"seeAlsoSections":[{"anchor":"Route","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError"],"title":"Route","generated":true}],"kind":"symbol","metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"NVibeManeuver","kind":"identifier"}],"title":"NVibeManeuver","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeManeuver","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@NVDirectionKit@objc(cs)NVibeManeuver","modules":[{"name":"NVDirectionKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The maneuver of the walking step."}],"topicSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/type","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/modifier","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/bearing_before","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/bearing_after","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/coordinate","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/instruction","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/turn_direction","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/details"],"title":"Getting the maneuver attributes","anchor":"Getting-the-maneuver-attributes"},{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/init(from:)"],"title":"Initializers"}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibemaneuver"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvdirectionkit\/nvibemaneuver"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/type":{"role":"symbol","abstract":[{"type":"text","text":"The type of the maneuver."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/type","title":"type","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/type"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/coordinate":{"abstract":[{"type":"text","text":"The coordinate of the maneuver."}],"kind":"symbol","title":"coordinate","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/coordinate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"coordinate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/coordinate","role":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/Se":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/Se","title":"Swift.Decodable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError":{"abstract":[{"text":"Constants that describe error related to walking route calculation.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RouteError"}],"role":"symbol","url":"\/documentation\/nvdirectionkit\/routeerror","navigatorTitle":[{"kind":"identifier","text":"RouteError"}],"type":"topic","title":"RouteError","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","url":"\/documentation\/nvdirectionkit\/nvibestep","type":"topic","title":"NVibeStep","role":"symbol","abstract":[{"text":"The walking step inside walking leg.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeStep","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH","title":"Swift.Hashable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg":{"abstract":[{"type":"text","text":"The walking leg inside walking route."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeLeg","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeleg","navigatorTitle":[{"kind":"identifier","text":"NVibeLeg"}],"role":"symbol","type":"topic","title":"NVibeLeg"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/modifier":{"title":"modifier","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/modifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/modifier","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"text":"The modifier of the maneuver.","type":"text"}],"kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuverDetail":{"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuverdetail","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","kind":"symbol","title":"NVibeManeuverDetail","abstract":[{"type":"text","text":"The detail inside maneuver."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeManeuverDetail"}],"navigatorTitle":[{"text":"NVibeManeuverDetail","kind":"identifier"}],"type":"topic"},"doc://com.nvibe.NVDirectionKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/details":{"type":"topic","role":"symbol","abstract":[{"text":"The details of the maneuver.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/details","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/details","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"details"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuverDetail","kind":"typeIdentifier","text":"NVibeManeuverDetail"},{"text":"]","kind":"text"}],"kind":"symbol","title":"details"},"doc://com.nvibe.NVDirectionKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute":{"abstract":[{"text":"The walking route received when requesting walking route.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRoute"}],"title":"NVibeRoute","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute","role":"symbol","navigatorTitle":[{"text":"NVibeRoute","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption":{"title":"NVibeRouteOption","url":"\/documentation\/nvdirectionkit\/nviberouteoption","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeRouteOption","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeRouteOption","kind":"identifier"}],"abstract":[{"type":"text","text":"The option for walking route."}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/objc(cs)NSObject":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/instruction":{"title":"instruction","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"instruction"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"text":"The instruction of the maneuver.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/instruction","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/instruction","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/bearing_before":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/bearing_before","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The angle before the maneuver."}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/bearing_before","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bearing_before"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"bearing_before"},"doc://com.nvibe.NVDirectionKit/objc(pl)NSObject":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver":{"title":"NVibeManeuver","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","abstract":[{"type":"text","text":"The maneuver of the walking step."}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeManeuver","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeManeuver"}]},"doc://com.nvibe.NVDirectionKit/SE":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/turn_direction":{"abstract":[{"type":"text","text":"The turn direction in hour of the maneuver."}],"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/turn_direction","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"turn_direction"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"turn_direction","kind":"symbol","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/turn_direction"},"doc://com.nvibe.NVDirectionKit/SQ":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/bearing_after":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/bearing_after","abstract":[{"type":"text","text":"The angle after the maneuver."}],"role":"symbol","title":"bearing_after","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bearing_after"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/bearing_after"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/init(from:)":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/init(from:)","url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/init(from:)","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[],"kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"NVibeManeuver"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"NVibeManeuver","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"NVibeManeuver","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":null},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Route","title":"Route","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeManeuver"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title","op":"replace","value":"NVibeStep"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments","value":[{"kind":"identifier","text":"NVibeStep"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NVibeStep"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/title","value":"NVibeLeg"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/fragments","value":[{"text":"NVibeLeg","kind":"identifier"}]},{"op":"replace","value":[{"text":"NVibeLeg","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/title","value":"NVibeManeuverDetail"},{"value":[{"text":"NVibeManeuverDetail","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NVibeManeuverDetail"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/title","value":"NVibeRoute"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/fragments","value":[{"text":"NVibeRoute","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"NVibeRoute"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/title","op":"replace","value":"NVibeRouteOption"},{"op":"replace","value":[{"kind":"identifier","text":"NVibeRouteOption"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/fragments"},{"value":[{"text":"NVibeRouteOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/title","value":"NVibeManeuver","op":"replace"},{"value":[{"kind":"identifier","text":"NVibeManeuver"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/fragments"},{"value":[{"kind":"identifier","text":"NVibeManeuver"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/navigatorTitle"}]}]}