{"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/departureStop","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/arrivalStop","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/transitMode","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/distance","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/duration","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/stopNumber","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/stops","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/coordinates","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/headsign","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/textColor","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/backgroundColor","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/type","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/line","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/departureTime","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/Mode"],"anchor":"Getting-the-walking-information-attributes","title":"Getting the walking information attributes"},{"anchor":"Getting-the-GPX-from-the-transit-multimodal-step","title":"Getting the GPX from the transit multimodal step","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/toGPX(speed:)"]},{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/arrivalRef","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/departureRef"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"seeAlsoSections":[{"title":"MultimodalRoute","anchor":"MultimodalRoute","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError"]}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibetransitinformation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nvdirectionkit\/nvibetransitinformation"]}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeTransitInformation","kind":"identifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","symbolKind":"class","modules":[{"name":"NVDirectionKit"}],"navigatorTitle":[{"text":"NVibeTransitInformation","kind":"identifier"}],"roleHeading":"Class","title":"NVibeTransitInformation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeTransitInformation","kind":"identifier"}],"externalID":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/distance":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/distance","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"distance"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"distance","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/distance","abstract":[{"type":"text","text":"The distance in meter of the transit multimodal step."}]},"doc://com.nvibe.NVDirectionKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation":{"navigatorTitle":[{"text":"NVibeTransitInformation","kind":"identifier"}],"title":"NVibeTransitInformation","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeTransitInformation","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeMultimodalStep","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","abstract":[{"type":"text","text":"The multimodal step inside multimodal route."}],"type":"topic","title":"NVibeMultimodalStep","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalStep"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep","kind":"symbol","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/arrivalStop":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/arrivalStop","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"arrivalStop"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier","text":"NVibeLocation"}],"title":"arrivalStop","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/arrivalstop","abstract":[{"type":"text","text":"The arrival stop of the transit multimodal step."}]},"doc://com.nvibe.NVDirectionKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/departureStop":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/departureStop","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"departureStop","kind":"identifier"},{"kind":"text","text":": "},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"}],"title":"departureStop","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/departurestop","abstract":[{"type":"text","text":"The departure stop of the transit multimodal step."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/duration":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/duration","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"duration","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"title":"duration","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/duration","abstract":[{"text":"The duration in second of the transit multimodal step.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/Mode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Mode","kind":"identifier"}],"title":"NVibeTransitInformation.Mode","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/Mode","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Mode"}],"abstract":[{"text":"Constants that describe the mode of the transit multimodal step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/mode"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/textColor":{"abstract":[{"text":"The text color of the icon’s transit.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"textColor","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/textColor","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/textcolor","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/line":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The line of the transit."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"line","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"line","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/line","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/line"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData":{"title":"NVibeTransitionData","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata","navigatorTitle":[{"kind":"identifier","text":"NVibeTransitionData"}],"abstract":[{"text":"The transition data for walking route.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeTransitionData"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/coordinates":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"coordinates","kind":"identifier"},{"kind":"text","text":": ["},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":"]"}],"abstract":[{"text":"The list of coordinates representing the transit mulitmodal step.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/coordinates","role":"symbol","kind":"symbol","title":"coordinates","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/coordinates"},"doc://com.nvibe.NVDirectionKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/departureTime":{"url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/departuretime","abstract":[{"type":"text","text":"The departure time of the transit."}],"title":"departureTime","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"departureTime","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/departureTime","role":"symbol"},"doc://com.nvibe.NVDirectionKit/objc(pl)NSObject":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation":{"abstract":[{"text":"The information describing a multimodal step.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","role":"symbol","title":"NVibeMultimodalStepInformation","navigatorTitle":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation"},"doc://com.nvibe.NVDirectionKit/s7CVarArgP":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeWalkingInformation","kind":"identifier"}],"title":"NVibeWalkingInformation","abstract":[{"text":"The walking information describing a walking multimodal step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/type":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"type","abstract":[{"type":"text","text":"The type of the transit."}],"url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/type","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/type","type":"topic","kind":"symbol","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/arrivalRef":{"role":"symbol","abstract":[{"text":"The indoor map id after the transit multimodal step.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/arrivalRef","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/arrivalref","kind":"symbol","title":"arrivalRef","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"arrivalRef"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/stops":{"abstract":[{"type":"text","text":"The stops along the transit multimodal step."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"stops","kind":"identifier"},{"kind":"text","text":": ["},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":"]","kind":"text"}],"title":"stops","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/stops","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/stops","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/headsign":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/headsign","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headsign"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"headsign","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/headsign","abstract":[{"text":"The direction of the transit.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/SQ":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/backgroundColor":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/backgroundColor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"backgroundColor","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/backgroundcolor","abstract":[{"text":"The background color of the icon’s transit.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError":{"url":"\/documentation\/nvdirectionkit\/multimodalerror","abstract":[{"text":"Constants that describe error related to multimodal route calculation.","type":"text"}],"title":"MultimodalError","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultimodalError","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultimodalError"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/stopNumber":{"url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/stopnumber","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/stopNumber","abstract":[{"text":"The number of stops of the transit multimodal step.","type":"text"}],"role":"symbol","title":"stopNumber","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/toGPX(speed:)":{"role":"symbol","abstract":[{"type":"text","text":"Returns a "},{"type":"codeVoice","code":"String"},{"text":" value representing the GPX of the transit multimodal step.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toGPX","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"speed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/togpx(speed:)","title":"toGPX(speed:)","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/toGPX(speed:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute":{"url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalRoute"}],"title":"NVibeMultimodalRoute","role":"symbol","abstract":[{"text":"The multimodal route received when requesting multimodal route.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalRoute"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/departureRef":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/departureRef","type":"topic","abstract":[{"type":"text","text":"The indoor map id before the transit multimodal step."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"departureRef"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/departureref","title":"departureRef","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/transitMode":{"abstract":[{"text":"The mode of the transit multimodal step.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"transitMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"NVibeTransitInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14NVDirectionKit23NVibeTransitInformationC4ModeO","kind":"typeIdentifier","text":"Mode"}],"title":"transitMode","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/transitMode","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/transitmode","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"NVibeTransitInformation","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"NVibeTransitInformation"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"NVibeTransitInformation","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData"],"anchor":"MultimodalRoute","title":"MultimodalRoute"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeTransitInformation","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NVibeMultimodalStepInformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStepInformation"}]}]}},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/title","value":"NVibeTransitInformation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/fragments","value":[{"kind":"identifier","text":"NVibeTransitInformation"}]},{"value":[{"text":"NVibeTransitInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/title","value":"NVibeMultimodalStep"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/fragments","value":[{"kind":"identifier","text":"NVibeMultimodalStep"}]},{"op":"replace","value":[{"text":"NVibeMultimodalStep","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/navigatorTitle"},{"value":"NVibeTransitionData","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/title"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/fragments","op":"replace","value":[{"text":"NVibeTransitionData","kind":"identifier"}]},{"value":[{"text":"NVibeTransitionData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/navigatorTitle","op":"replace"},{"value":"NVibeMultimodalStepInformation","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/title"},{"value":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/fragments"},{"value":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/title","value":"NVibeWalkingInformation","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/fragments","value":[{"text":"NVibeWalkingInformation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeWalkingInformation"}]},{"value":"NVibeMultimodalRoute","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/fragments","value":[{"text":"NVibeMultimodalRoute","kind":"identifier"}]},{"op":"replace","value":[{"text":"NVibeMultimodalRoute","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}