{"abstract":[{"type":"text","text":"The multimodal step inside multimodal route."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeMultimodalStep"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Getting the multimodal step attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/startAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/endAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/distance","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/duration","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/information"],"anchor":"Getting-the-multimodal-step-attributes"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/isIndoorStep()","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/isTransitStep()","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/isWalkingStep()","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/isWalkingTransitChangeStep()"],"title":"Instance Methods"}],"seeAlsoSections":[{"anchor":"MultimodalRoute","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError"],"title":"MultimodalRoute"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibemultimodalstep"]},{"paths":["\/documentation\/nvdirectionkit\/nvibemultimodalstep"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeMultimodalStep","kind":"identifier"}],"externalID":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","role":"symbol","modules":[{"name":"NVDirectionKit"}],"title":"NVibeMultimodalStep","roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"NVibeMultimodalStep","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation":{"abstract":[{"text":"The information describing a multimodal step.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","role":"symbol","title":"NVibeMultimodalStepInformation","navigatorTitle":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep/distance":{"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/distance","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep\/distance","abstract":[{"text":"The distance in meter of the multimodal step.","type":"text"}],"role":"symbol","title":"distance","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep/isIndoorStep()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isIndoorStep","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic","role":"symbol","title":"isIndoorStep()","url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep\/isindoorstep()","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/isIndoorStep()","abstract":[{"type":"text","text":"Returns a Boolean value indicating wheter the multimodal step is a walking indoor multimodal step."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep/endAddress":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/endAddress","abstract":[{"text":"The end location of the multimodal step.","type":"text"}],"role":"symbol","title":"endAddress","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"endAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep\/endaddress"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep/duration":{"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep\/duration","abstract":[{"type":"text","text":"The duration in second of the multimodal step."}],"role":"symbol","title":"duration","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep/isWalkingTransitChangeStep()":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/isWalkingTransitChangeStep()","role":"symbol","title":"isWalkingTransitChangeStep()","abstract":[{"text":"Returns a Boolean value indicating wheter the multimodal step is a walking transit change multimodal step.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isWalkingTransitChangeStep","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep\/iswalkingtransitchangestep()"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError":{"url":"\/documentation\/nvdirectionkit\/multimodalerror","abstract":[{"text":"Constants that describe error related to multimodal route calculation.","type":"text"}],"title":"MultimodalError","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultimodalError","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultimodalError"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeMultimodalStep","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","abstract":[{"type":"text","text":"The multimodal step inside multimodal route."}],"type":"topic","title":"NVibeMultimodalStep","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalStep"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep","kind":"symbol","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeWalkingInformation","kind":"identifier"}],"title":"NVibeWalkingInformation","abstract":[{"text":"The walking information describing a walking multimodal step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep/isWalkingStep()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isWalkingStep"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","role":"symbol","title":"isWalkingStep()","url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep\/iswalkingstep()","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/isWalkingStep()","abstract":[{"text":"Returns a Boolean value indicating wheter the multimodal step is a walking multimodal step.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep/isTransitStep()":{"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/isTransitStep()","title":"isTransitStep()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isTransitStep","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns a Boolean value indicating wheter the multimodal step is a transit multimodal step."}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep\/istransitstep()","kind":"symbol","role":"symbol"},"doc://com.nvibe.NVDirectionKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject","title":"NSObject"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation":{"navigatorTitle":[{"text":"NVibeTransitInformation","kind":"identifier"}],"title":"NVibeTransitInformation","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeTransitInformation","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep/startAddress":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/startAddress","abstract":[{"text":"The start location of the multimodal step.","type":"text"}],"role":"symbol","title":"startAddress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAddress"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier","text":"NVibeLocation"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep\/startaddress"},"doc://com.nvibe.NVDirectionKit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH","title":"Swift.Hashable"},"doc://com.nvibe.NVDirectionKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData":{"title":"NVibeTransitionData","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata","navigatorTitle":[{"kind":"identifier","text":"NVibeTransitionData"}],"abstract":[{"text":"The transition data for walking route.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeTransitionData"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData"},"doc://com.nvibe.NVDirectionKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ","title":"Swift.Equatable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute":{"url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalRoute"}],"title":"NVibeMultimodalRoute","role":"symbol","abstract":[{"text":"The multimodal route received when requesting multimodal route.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalRoute"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep/information":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/information","abstract":[{"type":"text","text":"The information about the multimodal step."}],"role":"symbol","title":"information","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"information"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStepInformation","text":"NVibeMultimodalStepInformation"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep\/information"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"NVibeMultimodalStep","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"NVibeMultimodalStep","kind":"identifier"}]},{"value":[{"text":"NVibeMultimodalStep","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"value":[{"generated":true,"title":"MultimodalRoute","anchor":"MultimodalRoute","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData"]}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeMultimodalStep","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/title","value":"NVibeMultimodalStepInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/fragments","value":[{"kind":"identifier","text":"NVibeMultimodalStepInformation"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/navigatorTitle","value":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/title","value":"NVibeMultimodalStep"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/fragments","value":[{"text":"NVibeMultimodalStep","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/navigatorTitle","op":"replace","value":[{"text":"NVibeMultimodalStep","kind":"identifier"}]},{"value":"NVibeWalkingInformation","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/fragments","value":[{"kind":"identifier","text":"NVibeWalkingInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeWalkingInformation"}]},{"op":"replace","value":"NVibeTransitInformation","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"NVibeTransitInformation"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeTransitInformation"}]},{"value":"NVibeTransitionData","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/title"},{"value":[{"kind":"identifier","text":"NVibeTransitionData"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/navigatorTitle","value":[{"text":"NVibeTransitionData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/title","op":"replace","value":"NVibeMultimodalRoute"},{"value":[{"kind":"identifier","text":"NVibeMultimodalRoute"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/navigatorTitle","value":[{"text":"NVibeMultimodalRoute","kind":"identifier"}]}]}]}