{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode\/hashValue"},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode\/RawRepresentable-Implementations"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibewalkinginformation\/mode\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"extendedModule":"Swift","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"symbolKind":"property","title":"hashValue","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::s:14NVDirectionKit23NVibeWalkingInformationC4ModeO","roleHeading":"Instance Property","modules":[{"name":"NVDirectionKit","relatedModules":["Swift"]}]},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/Mode":{"navigatorTitle":[{"kind":"identifier","text":"Mode"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Mode","kind":"identifier"}],"abstract":[{"text":"Constants that describe the mode of the walking multimodal step.","type":"text"}],"kind":"symbol","type":"topic","title":"NVibeWalkingInformation.Mode","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/mode"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/Mode/hashValue":{"title":"hashValue","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/mode\/hashvalue","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode\/hashValue","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeWalkingInformation","kind":"identifier"}],"title":"NVibeWalkingInformation","abstract":[{"text":"The walking information describing a walking multimodal step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/Mode/RawRepresentable-Implementations":{"role":"collectionGroup","kind":"article","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/mode\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode\/RawRepresentable-Implementations","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/title","value":"NVibeWalkingInformation","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/fragments","op":"replace","value":[{"kind":"identifier","text":"NVibeWalkingInformation"}]},{"value":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/navigatorTitle","op":"replace"}]}]}