{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMultimodalRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"startLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"endLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeFullWalking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute","text":"NVibeMultimodalRoute"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError","preciseIdentifier":"s:14NVDirectionKit15MultimodalErrorO","text":"MultimodalError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"startLocation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"departure of the route"}]}]},{"name":"endLocation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"arrival of the route"}]}]},{"name":"includeFullWalking","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"choose if you want full walking route include in multimodal result"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"return a list of "},{"type":"codeVoice","code":"NVibeMultimodalRoute"},{"type":"text","text":" or "},{"type":"codeVoice","code":"RouteError"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvdirection\/getmultimodalroute(from:to:includefullwalking:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getMultimodalRoute(from:to:includeFullWalking:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get multimodal (with transit) route"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMultimodalRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeFullWalking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"NVibeMultimodalRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"MultimodalError","preciseIdentifier":"s:14NVDirectionKit15MultimodalErrorO"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"getMultimodalRoute(from:to:includeFullWalking:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:14NVDirectionKit0A0C18getMultimodalRoute4from2to18includeFullWalking10completionyAA13NVibeLocationC_AJSbySayAA0ldE0CGSg_AA0D5ErrorOSgtctF","modules":[{"name":"NVDirectionKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"]]},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"role":"symbol","title":"NVDirection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"abstract":[{"type":"text","text":"NVDirection is used to get multiple data from our API"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVDirection"}],"url":"\/documentation\/nvdirectionkit\/nvdirection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"role":"symbol","title":"NVibeLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeLocation"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeLocation"}],"url":"\/documentation\/nvdirectionkit\/nvibelocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getMultimodalRoute(from:to:includeFullWalking:completion:)":{"role":"symbol","title":"getMultimodalRoute(from:to:includeFullWalking:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMultimodalRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeFullWalking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"NVibeMultimodalRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"MultimodalError","preciseIdentifier":"s:14NVDirectionKit15MultimodalErrorO"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get multimodal (with transit) route"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getMultimodalRoute(from:to:includeFullWalking:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getmultimodalroute(from:to:includefullwalking:completion:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","title":"NVDirectionKit","abstract":[{"type":"text","text":"Obtain route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute":{"role":"symbol","title":"NVibeMultimodalRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalRoute"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalRoute"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError":{"role":"symbol","title":"MultimodalError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimodalError"}],"abstract":[{"type":"text","text":"MultimodalError describes error related to multimodal route calculation"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultimodalError"}],"url":"\/documentation\/nvdirectionkit\/multimodalerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title","value":"NVDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments","value":[{"kind":"identifier","text":"NVDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","value":"NVibeLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","value":[{"kind":"identifier","text":"NVibeLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/title","value":"NVibeMultimodalRoute"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/fragments","value":[{"kind":"identifier","text":"NVibeMultimodalRoute"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}