{"sections":[],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/isWalkingStep()","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isWalkingStep","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"NVDirectionKit"}],"roleHeading":"Instance Method","externalID":"s:14NVDirectionKit19NVibeMultimodalStepC09isWalkingE0SbyF","role":"symbol","title":"isWalkingStep()","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isWalkingStep","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"text":" if the multimodal step is a walking multimodal step or ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" if it is not."}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep"]]},"abstract":[{"type":"text","text":"Returns a Boolean value indicating wheter the multimodal step is a walking multimodal step."}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibemultimodalstep\/iswalkingstep()"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep/isWalkingStep()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isWalkingStep"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","role":"symbol","title":"isWalkingStep()","url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep\/iswalkingstep()","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/isWalkingStep()","abstract":[{"text":"Returns a Boolean value indicating wheter the multimodal step is a walking multimodal step.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeMultimodalStep","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","abstract":[{"type":"text","text":"The multimodal step inside multimodal route."}],"type":"topic","title":"NVibeMultimodalStep","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalStep"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep","kind":"symbol","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"NVibeMultimodalStep","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/title"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/fragments","op":"replace","value":[{"kind":"identifier","text":"NVibeMultimodalStep"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NVibeMultimodalStep"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}