{"seeAlsoSections":[{"title":"Global","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeProjection","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TokenError"}],"title":"TokenError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:14NVDirectionKit10TokenErrorO","modules":[{"name":"NVDirectionKit"}],"navigatorTitle":[{"kind":"identifier","text":"TokenError"}]},"abstract":[{"type":"text","text":"TokenError is a type error related to token"}],"sections":[],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH","doc:\/\/com.nvibe.NVDirectionKit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError\/INVALID_TOKEN","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError\/MAX_ACTIVE_USER_REACHED","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError\/UNKNOW"]},{"title":"Initializers","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError\/Equatable-Implementations","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/tokenerror"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TokenError"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"INVALID_TOKEN: your token is malformed or expired"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MAX_ACTIVE_USER_REACHED: you reached the maximum active user allowed by your key"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"UNKNOW: an unknow error occured"}]}]}]}]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/TokenError":{"role":"symbol","title":"TokenError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TokenError"}],"abstract":[{"type":"text","text":"TokenError is a type error related to token"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TokenError"}],"url":"\/documentation\/nvdirectionkit\/tokenerror"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation":{"role":"symbol","title":"NVibeIndoorLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeIndoorLocation"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeIndoorLocation"}],"url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"role":"symbol","title":"NVibeLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeLocation"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeLocation"}],"url":"\/documentation\/nvdirectionkit\/nvibelocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/TokenError/INVALID_TOKEN":{"role":"symbol","title":"TokenError.INVALID_TOKEN","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"INVALID_TOKEN"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError\/INVALID_TOKEN","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/tokenerror\/invalid_token"},"doc://com.nvibe.NVDirectionKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SY"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeProjection":{"role":"symbol","title":"NVibeProjection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeProjection"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeProjection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeProjection"}],"url":"\/documentation\/nvdirectionkit\/nvibeprojection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/TokenError/UNKNOW":{"role":"symbol","title":"TokenError.UNKNOW","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UNKNOW"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError\/UNKNOW","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/tokenerror\/unknow"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/TokenError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/tokenerror\/init(rawvalue:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet":{"role":"symbol","title":"SideStreet","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideStreet"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SideStreet"}],"url":"\/documentation\/nvdirectionkit\/sidestreet"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","title":"NVDirectionKit","abstract":[{"type":"text","text":"Obtain route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/TokenError/MAX_ACTIVE_USER_REACHED":{"role":"symbol","title":"TokenError.MAX_ACTIVE_USER_REACHED","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"MAX_ACTIVE_USER_REACHED"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError\/MAX_ACTIVE_USER_REACHED","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/tokenerror\/max_active_user_reached"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/TokenError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/tokenerror\/equatable-implementations"},"doc://com.nvibe.NVDirectionKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ"},"doc://com.nvibe.NVDirectionKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/TokenError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/TokenError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/tokenerror\/rawrepresentable-implementations"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle":{"role":"symbol","title":"NVibeObstacle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeObstacle"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeObstacle"}],"url":"\/documentation\/nvdirectionkit\/nvibeobstacle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/title","value":"NVibeIndoorLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/fragments","value":[{"kind":"identifier","text":"NVibeIndoorLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","value":"NVibeLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","value":[{"kind":"identifier","text":"NVibeLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeProjection\/title","value":"NVibeProjection"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeProjection\/fragments","value":[{"kind":"identifier","text":"NVibeProjection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/title","value":"NVibeObstacle"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/fragments","value":[{"kind":"identifier","text":"NVibeObstacle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}