{"metadata":{"symbolKind":"property","title":"position","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"position"},{"kind":"text","text":": ["},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"externalID":"s:14NVDirectionKit21NVibeInformationPointC8positionSaySdGvp","roleHeading":"Instance Property","modules":[{"name":"NVDirectionKit"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"anchor":"Getting-the-information-point-attributes","generated":true,"title":"Getting the information point attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/information","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/projection"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibeinformationpoint\/position"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/position"},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeInformationPoint":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeInformationPoint"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint","url":"\/documentation\/nvdirectionkit\/nvibeinformationpoint","type":"topic","title":"NVibeInformationPoint","role":"symbol","abstract":[{"type":"text","text":"The information point along a route."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeInformationPoint"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeInformationPoint/projection":{"title":"projection","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/projection","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"projection","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":"]","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeinformationpoint\/projection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","kind":"symbol","abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"Version:"}]},{"type":"text","text":" 0.6.1"}],"role":"collection","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeInformationPoint/information":{"url":"\/documentation\/nvdirectionkit\/nvibeinformationpoint\/information","title":"information","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"information"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/information","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeInformationPoint/position":{"title":"position","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/position","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"position"},{"text":": [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":"]"}],"kind":"symbol","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeinformationpoint\/position"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"NVibeInformationPoint","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/title"},{"value":[{"text":"NVibeInformationPoint","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/fragments"},{"value":[{"kind":"identifier","text":"NVibeInformationPoint"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/navigatorTitle"}]}]}