{"abstract":[{"text":"The links used by alternative walking multimodal step.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibewalkinginformation\/links"]}],"metadata":{"externalID":"s:14NVDirectionKit23NVibeWalkingInformationC5linksSayAA4LinkCGSgvp","modules":[{"name":"NVDirectionKit"}],"symbolKind":"property","title":"links","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"links","kind":"identifier"},{"kind":"text","text":": ["},{"text":"Link","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)Link"},{"text":"]?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation"]]},"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/links","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"links","kind":"identifier"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)Link","text":"Link"},{"kind":"text","text":"]?"}],"languages":["swift"]}]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/links":{"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/links","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/links","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"links"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)Link","kind":"typeIdentifier","text":"Link"},{"text":"]?","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"text":"The links used by alternative walking multimodal step.","type":"text"}],"title":"links","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeWalkingInformation","kind":"identifier"}],"title":"NVibeWalkingInformation","abstract":[{"text":"The walking information describing a walking multimodal step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/Link":{"url":"\/documentation\/nvdirectionkit\/link","type":"topic","title":"Link","navigatorTitle":[{"kind":"identifier","text":"Link"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Link","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link","abstract":[{"type":"text","text":"The link along an alternative walking route."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/title","op":"replace","value":"NVibeWalkingInformation"},{"op":"replace","value":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/fragments"},{"value":[{"text":"NVibeWalkingInformation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/title","value":"Link","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/fragments","value":[{"text":"Link","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"Link","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/navigatorTitle"}]}]}