{"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/Mode-swift.enum\/hashValue"],"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/Mode-swift.enum\/hash(into:)"],"anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/Mode-swift.enum"]]},"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation\/mode-swift.enum\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","metadata":{"title":"RawRepresentable Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"NVDirectionKit"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/Mode-swift.enum\/RawRepresentable-Implementations"},"sections":[],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation/Mode-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Mode"}],"title":"NVibeMultimodalStepInformation.Mode","abstract":[{"type":"text","text":"Constants that describe the mode of the multimodal step."}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation\/mode-swift.enum","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/Mode-swift.enum","type":"topic","kind":"symbol","navigatorTitle":[{"text":"Mode","kind":"identifier"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation":{"abstract":[{"text":"The information describing a multimodal step.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","role":"symbol","title":"NVibeMultimodalStepInformation","navigatorTitle":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation/Mode-swift.enum/hashValue":{"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/Mode-swift.enum\/hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"type":"topic","url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation\/mode-swift.enum\/hashvalue","title":"hashValue","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation/Mode-swift.enum/hash(into:)":{"type":"topic","url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation\/mode-swift.enum\/hash(into:)","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/Mode-swift.enum\/hash(into:)","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"title":"hash(into:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"NVibeMultimodalStepInformation","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/title"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/fragments","value":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeMultimodalStepInformation"}]}]}]}