{"abstract":[{"type":"text","text":"The distance in meter of the walking route."}],"kind":"symbol","identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/distance","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"distance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nviberoute\/distance"]}],"seeAlsoSections":[{"generated":true,"title":"Getting the walking route attributes","anchor":"Getting-the-walking-route-attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/startAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/endAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/duration","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/legs","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/geometry","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/alternativeGeometry","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/coordinates","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/option"]}],"metadata":{"title":"distance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"distance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"symbolKind":"property","role":"symbol","externalID":"s:14NVDirectionKit10NVibeRouteC8distanceSdvp","roleHeading":"Instance Property","modules":[{"name":"NVDirectionKit"}]},"sections":[],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/alternativeGeometry":{"abstract":[{"type":"text","text":"The alternative geometry (encoded with an accuracy of 6) of the walking route."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alternativeGeometry"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"alternativeGeometry","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/alternativeGeometry","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/alternativegeometry","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/coordinates":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"coordinates","kind":"identifier"},{"text":": [","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"abstract":[{"text":"The list of coordinates representing the walking route (decoded geometry).","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/coordinates","role":"symbol","kind":"symbol","title":"coordinates","url":"\/documentation\/nvdirectionkit\/nviberoute\/coordinates"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/geometry":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/geometry","url":"\/documentation\/nvdirectionkit\/nviberoute\/geometry","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"geometry","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","abstract":[{"text":"The geometry (encoded with an accuracy of 6) of the walking route.","type":"text"}],"kind":"symbol","title":"geometry","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/distance":{"abstract":[{"text":"The distance in meter of the walking route.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"distance","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"distance","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/distance","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/distance","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute":{"abstract":[{"text":"The walking route received when requesting walking route.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRoute"}],"title":"NVibeRoute","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute","role":"symbol","navigatorTitle":[{"text":"NVibeRoute","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/duration":{"kind":"symbol","abstract":[{"type":"text","text":"The duration in second of the walking route."}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/duration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"title":"duration","url":"\/documentation\/nvdirectionkit\/nviberoute\/duration","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/endAddress":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/endAddress","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/endaddress","abstract":[{"type":"text","text":"The end location of the walking route."}],"role":"symbol","kind":"symbol","title":"endAddress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"endAddress","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/legs":{"url":"\/documentation\/nvdirectionkit\/nviberoute\/legs","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/legs","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"legs"},{"text":": [","kind":"text"},{"text":"NVibeLeg","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLeg"},{"text":"]","kind":"text"}],"role":"symbol","abstract":[{"text":"The list of leg of the walking route.","type":"text"}],"kind":"symbol","title":"legs","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/startAddress":{"type":"topic","title":"startAddress","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"startAddress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"}],"abstract":[{"text":"The start location of the walking route.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nviberoute\/startaddress","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/startAddress","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/option":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/option","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"option","kind":"identifier"},{"kind":"text","text":": "},{"text":"NVibeRouteOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRouteOption"}],"title":"option","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nviberoute\/option","abstract":[{"text":"The option of the walking route.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"NVibeRoute","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/title"},{"value":[{"text":"NVibeRoute","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/fragments","op":"replace"},{"value":[{"text":"NVibeRoute","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/navigatorTitle","op":"replace"}]}]}