{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/link\/id"]}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link\/id","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"NVDirectionKit"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"externalID":"s:14NVDirectionKit4LinkC2idSivp","role":"symbol","symbolKind":"property","title":"id"},"abstract":[{"type":"text","text":"The id of the link."}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/Link":{"url":"\/documentation\/nvdirectionkit\/link","type":"topic","title":"Link","navigatorTitle":[{"kind":"identifier","text":"Link"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Link","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link","abstract":[{"type":"text","text":"The link along an alternative walking route."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}],"kind":"symbol","type":"topic","title":"NVDirectionKit","role":"collection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/Link/id":{"url":"\/documentation\/nvdirectionkit\/link\/id","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link\/id","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"The id of the link.","type":"text"}],"kind":"symbol","title":"id","type":"topic"}},"variantOverrides":[{"patch":[{"value":"Link","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/title"},{"value":[{"kind":"identifier","text":"Link"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/fragments"},{"value":[{"kind":"identifier","text":"Link"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}