{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/obstacles"},"metadata":{"title":"obstacles","role":"symbol","modules":[{"name":"NVDirectionKit"}],"externalID":"s:14NVDirectionKit9NVibeStepC9obstaclesSayAA0C8ObstacleCGSgvp","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"obstacles"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeObstacle","text":"NVibeObstacle","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"symbolKind":"property"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The obstacles along the walking step."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"obstacles"},{"text":": [","kind":"text"},{"text":"NVibeObstacle","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeObstacle"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibestep\/obstacles"],"traits":[{"interfaceLanguage":"swift"}]}],"seeAlsoSections":[{"title":"Getting the walking step attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/distance","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/duration","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/maneuver","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/walkingSide","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/streetName","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/geometry","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/coordinates"],"anchor":"Getting-the-walking-step-attributes","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep"]]},"kind":"symbol","references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/streetName":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"streetName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The name of the street along the walking step."}],"title":"streetName","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/streetName","url":"\/documentation\/nvdirectionkit\/nvibestep\/streetname","type":"topic","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","url":"\/documentation\/nvdirectionkit\/nvibestep","type":"topic","title":"NVibeStep","role":"symbol","abstract":[{"text":"The walking step inside walking leg.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeStep","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/duration":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"abstract":[{"type":"text","text":"The duration in second of the walking step."}],"title":"duration","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/duration","url":"\/documentation\/nvdirectionkit\/nvibestep\/duration","type":"topic","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/maneuver":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maneuver","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuver","text":"NVibeManeuver","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The maneuver of the walking step."}],"title":"maneuver","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/maneuver","url":"\/documentation\/nvdirectionkit\/nvibestep\/maneuver","type":"topic","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/walkingSide":{"url":"\/documentation\/nvdirectionkit\/nvibestep\/walkingside","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/walkingSide","title":"walkingSide","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The side of the street along the walking step."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"walkingSide","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/distance":{"url":"\/documentation\/nvdirectionkit\/nvibestep\/distance","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/distance","title":"distance","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The distance in meter of the walking step."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"distance","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/obstacles":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"obstacles","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NVibeObstacle","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeObstacle","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The obstacles along the walking step."}],"title":"obstacles","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/obstacles","url":"\/documentation\/nvdirectionkit\/nvibestep\/obstacles","type":"topic","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/geometry":{"url":"\/documentation\/nvdirectionkit\/nvibestep\/geometry","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/geometry","title":"geometry","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The geometry (encoded with an accuracy of 6) of the walking step."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"geometry"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/coordinates":{"url":"\/documentation\/nvdirectionkit\/nvibestep\/coordinates","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/coordinates","title":"coordinates","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The list of coordinates representing the walking step (decoded geometry)."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"coordinates","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":"]","kind":"text"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","kind":"symbol","abstract":[{"type":"text","text":"The obstacle along a route."}],"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeobstacle","navigatorTitle":[{"text":"NVibeObstacle","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeObstacle","kind":"identifier"}],"title":"NVibeObstacle"}},"variantOverrides":[{"patch":[{"value":"NVibeStep","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title","op":"replace"},{"value":[{"kind":"identifier","text":"NVibeStep"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments"},{"op":"replace","value":[{"text":"NVibeStep","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/navigatorTitle"},{"value":"NVibeObstacle","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/fragments","value":[{"text":"NVibeObstacle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/navigatorTitle","value":[{"text":"NVibeObstacle","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}