{"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"details"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","text":"NVibeManeuverDetail","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuverDetail"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Property","externalID":"s:14NVDirectionKit13NVibeManeuverC7detailsSayAA0cD6DetailCGvp","title":"details","modules":[{"name":"NVDirectionKit"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"details","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuverDetail","kind":"typeIdentifier","text":"NVibeManeuverDetail"},{"kind":"text","text":"]"}],"symbolKind":"property"},"abstract":[{"text":"The details of the maneuver.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibemaneuver\/details"]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/type","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/modifier","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/bearing_before","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/bearing_after","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/coordinate","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/instruction","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/turn_direction"],"title":"Getting the maneuver attributes","anchor":"Getting-the-maneuver-attributes"}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/details","interfaceLanguage":"swift"},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/details":{"type":"topic","role":"symbol","abstract":[{"text":"The details of the maneuver.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/details","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/details","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"details"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuverDetail","kind":"typeIdentifier","text":"NVibeManeuverDetail"},{"text":"]","kind":"text"}],"kind":"symbol","title":"details"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuverDetail":{"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuverdetail","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","kind":"symbol","title":"NVibeManeuverDetail","abstract":[{"type":"text","text":"The detail inside maneuver."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeManeuverDetail"}],"navigatorTitle":[{"text":"NVibeManeuverDetail","kind":"identifier"}],"type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/coordinate":{"abstract":[{"type":"text","text":"The coordinate of the maneuver."}],"kind":"symbol","title":"coordinate","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/coordinate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"coordinate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/coordinate","role":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/instruction":{"title":"instruction","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"instruction"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"text":"The instruction of the maneuver.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/instruction","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/instruction","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/turn_direction":{"abstract":[{"type":"text","text":"The turn direction in hour of the maneuver."}],"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/turn_direction","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"turn_direction"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"turn_direction","kind":"symbol","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/turn_direction"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver":{"title":"NVibeManeuver","type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","abstract":[{"type":"text","text":"The maneuver of the walking step."}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeManeuver","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeManeuver"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/bearing_after":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/bearing_after","abstract":[{"type":"text","text":"The angle after the maneuver."}],"role":"symbol","title":"bearing_after","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bearing_after"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/bearing_after"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/modifier":{"title":"modifier","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/modifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/modifier","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"text":"The modifier of the maneuver.","type":"text"}],"kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/bearing_before":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/bearing_before","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The angle before the maneuver."}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/bearing_before","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bearing_before"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"bearing_before"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/type":{"role":"symbol","abstract":[{"type":"text","text":"The type of the maneuver."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/type","title":"type","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/type"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"NVibeManeuverDetail","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/title"},{"value":[{"kind":"identifier","text":"NVibeManeuverDetail"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/fragments"},{"value":[{"kind":"identifier","text":"NVibeManeuverDetail"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/title","value":"NVibeManeuver"},{"value":[{"kind":"identifier","text":"NVibeManeuver"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/navigatorTitle","value":[{"text":"NVibeManeuver","kind":"identifier"}]}]}]}