{"abstract":[{"text":"The access coordinate of the indoor location.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibeindoorlocation\/access"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/access","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Getting-the-indoor-location-attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/address","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/position","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/floor"],"generated":true,"title":"Getting the indoor location attributes"}],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"access","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"}],"title":"access","externalID":"s:14NVDirectionKit19NVibeIndoorLocationC6accessSo22CLLocationCoordinate2DVvp","modules":[{"name":"NVDirectionKit"}],"roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"access","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation/access":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"access","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation\/access","title":"access","abstract":[{"type":"text","text":"The access coordinate of the indoor location."}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/access"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation/position":{"kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/position","title":"position","url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation\/position","type":"topic","abstract":[{"type":"text","text":"The position coordinate of the indoor location."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation/floor":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"floor","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation\/floor","abstract":[{"text":"The floor of the indoor location.","type":"text"}],"title":"floor","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/floor"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation/address":{"kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/address","title":"address","url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation\/address","type":"topic","abstract":[{"type":"text","text":"The address of the indoor location."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"address"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/nvdirectionkit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","title":"NVDirectionKit","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.6.1","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation":{"url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation","abstract":[{"type":"text","text":"The address and coordinates of a indoor location."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeIndoorLocation"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeIndoorLocation"}],"role":"symbol","kind":"symbol","title":"NVibeIndoorLocation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/title","op":"replace","value":"NVibeIndoorLocation"},{"op":"replace","value":[{"text":"NVibeIndoorLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/fragments"},{"value":[{"kind":"identifier","text":"NVibeIndoorLocation"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}